title: Site
deletable: false
pages:
  template:
    - default
    - legal

fields:
  title:
    label: Title
    type:  text
  description:
    label: Site description
    validate:
      maxWords: 25
    type: markdown
    toolbar: hide
    width: 1/2
  keywords:
    label: Keywords
    type:  tags
    width: 1/2
  dropdownable:
    label: Pages with dropdown menus
    type: checkboxes
    options: visibleChildren
    width: 1/2
  lv3dropdown:
    label: Additional nav options
    type: checkbox
    text: display lv-3 pages in dropdown menu?
    width: 1/2
  copyright:
    label: Copyright
